# Generated by Django 5.1.4 on 2025-01-15 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('error_type', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('traceback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('response_status_code', models.IntegerField()),
                ('send_to', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in-app', 'In-App')], default='email', max_length=10)),
                ('error_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_log', to='monitor.errorlog')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_framework_api_key.apikey')),
            ],
        ),
    ]
