# Generated by Django 5.1.4 on 2025-01-31 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlog',
            old_name='send_to',
            new_name='sent_to',
        ),
    ]
